name: 'Discord Notification'
description: 'Greet someone and record the time'
inputs:
  status:
    required: true
  title:
    required: false
  description:
    required: false
  username:
    required: false
  mention:
    required: false
  mention_if:
    required: false
  url:
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'